### ISSUE TITLE
Hardware trait takes & references

### ISSUE THREAD

**Issue by richo** [idubrov/lcd#2]
Hi!

Thanks for this library, so far it looks really good. I was hoping maybe you could add some colour to why the `Hardware` trait takes & references instead of &mut. The HAL I am using treats flipping pins as being a mutative operation which meant I had to pull in RefCell which is a fair bit of overhead. Would you be comfortable wiht a PR to update the trait to &mut?

**Comment by idubrov** [comment]
Which reference are you referring to? I don't remember the details honestly, but I see that `Display` takes `Hardware` by [moving it](https://github.com/idubrov/lcd/blob/b62212d7441f916a9fcef7dad01279a30dcff6f8/src/lib.rs#L252-L256), which should allow "mutating" it. Also, all functions on `Hardware` trait take `&mut self`.

**Comment by richo** [comment]
Aha, thanks for getting back to me quickly. It looks like the latest release on crates.io is quite old and missing a lot of your patches. Is there any chance you could release a new one?

**Comment by idubrov** [comment]
Ah, right, I started updating for recent [RTIC](https://rtic.rs), I think, and haven't finished doing it.

I published current master as "alpha" version (since I don't know yet how good my changes are), https://crates.io/crates/lcd/0.4.0-alpha.0

**Comment by richo** [comment]
Thankyou! Very appreciated!
